name: app_todo_list
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  calendar_timeline: ^1.1.3
  flutter_slidable: ^3.1.1
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^3.8.0
  cloud_firestore: ^5.6.0
  fluttertoast: ^8.2.8
  firebase_auth: ^5.3.4

## flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#DFECDB"
  image: assets/images/splash_light.png
  color_dark: "#060E1E"
  image_dark: assets/images/splash_dark.png
  branding: assets/images/branding.png
  branding_dark: assets/images/branding.png

  android_12:
    image: assets/images/splash_light.png
    icon_background_color: "#DFECDB"
    image_dark: assets/images/splash_dark.png
    icon_background_color_dark: "#060E1E"
    branding: assets/images/branding.png
    branding_dark: assets/images/branding.png



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
